### PR TITLE
Corporate Proxy Support

### PR DESCRIPTION
**Pull request by kaue**
Implement Corporate Proxy Support

phantomEval('http://localhost:8000', function() {
  // Run this in webkit
  return window.location.href
}, function(err, results) {
  // Handle the results in node.js
  console.log(results)
}, '127.0.0.1:8080')

### CODE REVIEW

**Comment by shama** [comment]
Thanks! Could you make `proxyConfig` an optional argument? That will fix the tests.

**Comment by kaue** [comment]
@shama Done, but looks a little ugly from my point of view. =/
I guess the best implementation would be an options object.

:+1:

**Comment by shama** [comment]
Cool thanks, merged with modifications. Check out https://github.com/shama/phantom-eval#passing-in-options-to-phantomjs and let me know if that works for you.

**Comment by kaue** [comment]
Looks awsome! thanks @shama =)

**Pull request closed without merging**
